version: '2.1'
services:
  sender-server:
    container_name: sender
    build:
      context: ..
      dockerfile: ./sender/Dockerfile
    image: docker.io/alexk/sender:latest
    hostname: sender
    ports:
      - "8080:8080"
    networks:
      - send-receive-network
  receiver-server:
    container_name: receiver
    build:
      context: ..
      dockerfile: ./receiver/Dockerfile
    image: docker.io/alexk/receiver:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8070:8070"
    networks:
      - send-receive-network
networks:
  send-receive-network:
    driver: bridge